# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 20:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_sectionpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='cat_title',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
        ),
    ]
