# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_navpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navpage',
            name='body',
        ),
    ]
