# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 01:34
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20160303_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='cat_title_class',
            field=wagtail.wagtailcore.fields.RichTextField(default=''),
        ),
    ]
