# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 02:36
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_sectionpage_cat_title_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='category',
            field=wagtail.wagtailcore.fields.StreamField((('cat_title', wagtail.wagtailcore.blocks.CharBlock(classname='full')), ('cat_title_class', wagtail.wagtailcore.blocks.CharBlock(classname='full'))), default=''),
            preserve_default=False,
        ),
    ]
