# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20160304_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=models.TextField(),
        ),
    ]
