# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-08 21:25
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20160304_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='add_script',
            field=wagtail.wagtailcore.fields.StreamField((('script', wagtail.wagtailcore.blocks.CharBlock(classname='full')),), default=''),
            preserve_default=False,
        ),
    ]
