# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20160309_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='recent',
            field=models.TextField(),
        ),
    ]
