# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 02:27
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20160311_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('panel', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('add_script', wagtail.wagtailcore.blocks.RawHTMLBlock()))),
        ),
    ]
