# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 03:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20160311_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionpage',
            name='recent',
        ),
    ]
