# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-11 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_remove_sectionpage_recent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionpage',
            name='recently',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
