# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 10:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0010_change_on_delete_behaviour'),
        ('wagtailcore', '0023_alter_page_revision_on_delete_behaviour'),
        ('home', '0026_sectionpage_recently'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('category', wagtail.wagtailcore.fields.StreamField((('cat_title_class', wagtail.wagtailcore.blocks.CharBlock(classname='full')), ('cat_title', wagtail.wagtailcore.blocks.CharBlock(classname='full'))))),
                ('body', wagtail.wagtailcore.fields.StreamField((('panel', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('add_script', wagtail.wagtailcore.blocks.RawHTMLBlock())))),
                ('date', models.DateField(verbose_name='Post date')),
                ('feed_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
