# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-27 08:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_genericpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='script',
            field=wagtail.wagtailcore.fields.StreamField((('add_script', wagtail.wagtailcore.blocks.RawHTMLBlock()),), default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sectionpage',
            name='script',
            field=wagtail.wagtailcore.fields.StreamField((('add_script', wagtail.wagtailcore.blocks.RawHTMLBlock()),), default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genericpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('panel', wagtail.wagtailcore.blocks.RawHTMLBlock()),)),
        ),
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('panel', wagtail.wagtailcore.blocks.RawHTMLBlock()),)),
        ),
    ]
